#### import pytorch

In [2]:
import torch

In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

## create/Initialize a tensor
A tensor is often thought of as a generalized matrix. That is, it could be a 1-D matrix (a vector is actually such a tensor), a 3-D matrix (something like a cube of numbers), even a 0-D matrix (a single number), or a higher dimensional structure that is harder to visualize. The dimension of the tensor is called its rank.
```0d: 0
1d: [1,2,3,4,5]
2d (array inside array): [[1,2,3],[4,5,6]]
3d (array of matrices):[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]```

`device`: is where this array will be and will be used. is `cuda` then the array will be inside the GPU's RAM. if `cpu` it will be in the man system's RAM

`requires_grad`: if back-propagation will be run on this tensore this parameter should be true. basically for every hidden layer of a NN is a tensor which has `requires_grad=True` so that the parameters can be tuned using back-propagation.

In [15]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


#### Create an empty tensor with specific size
`size`: specifies the size of tensor. here is 3x3 matrix
`empty` means that the array is uninitialized. which mean any value might be there.

In [18]:
x = torch.empty(size=(3,3))

#### Create an tensor with specific size and initialize it to zero (create a zero matrix).

In [21]:
x = torch.zeros(size=(3,3))
x = torch.ones(size=(3,3))

#### Create an tensor with specific size and initialize it with random value (create a random tensor) from a uniform distribution.

In [ ]:
x = torch.rand(size=(3,3))

#### create an idenrtity matrix of size 5x5

In [25]:
x = torch.eye(5)
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### create a 1-D tensor
Returns a 1-D tensor of size `(end-start)/step` with values from the interval `[start, end)` taken with common difference step beginning from start.

In [27]:
x = torch.arange(start=0, end=10, step=2)
x

tensor([0, 2, 4, 6, 8])

In [28]:
x = torch.arange(start=10, end=0, step=-2)
x

tensor([10,  8,  6,  4,  2])

Returns a 1-D tensor of size `steps` which starts at `start` and ends at `end` (`[start,end]`) with `steps - 2` values in between with equal distance.

In [30]:
x = torch.linspace(start=0, end=1, steps=10)
x

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

#### careate an empty array and initialize it with value from a normally distributed number with `mean=0` and `standard deviation = 1`

In [32]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[ 0.7108,  2.1428, -0.2380, -0.3756, -0.8186]])

#### careate an empty array and initialize it with value from a uniform distributed number with `mean=0` and `standard deviation = 1`

In [34]:
torch.empty(size=(1,5)).uniform_(0,1)

tensor([[0.6851, 0.2475, 0.6612, 0.2469, 0.7192]])

The normal distribution is bell-shaped, which means value near the center of the distribution are more likely to occur as opposed to values on the tails of the distribution.
The uniform distribution is rectangular-shaped, which means every value in the distribution is equally likely to occur.

<img src='normal_uniform.JPG' />

#### Create a diagonal matrix
the diagonal values should be passed as vector

In [35]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## conver types of initialized tensor

In [38]:
tens = torch.arange(4)
tens

tensor([0, 1, 2, 3])

In [39]:
tens.bool()

tensor([False,  True,  True,  True])

In [40]:
tens.short() # convert to int16

tensor([0, 1, 2, 3], dtype=torch.int16)

In [42]:
tens.long() # convert to int64

tensor([0, 1, 2, 3])

In [44]:
tens.half() # convert to float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [45]:
tens.float() # convert to floar32

tensor([0., 1., 2., 3.])

In [46]:
tens.double() # convert to floar64

tensor([0., 1., 2., 3.], dtype=torch.float64)

## Conversino from numpy array to torch tensor 

In [47]:
import numpy as np

In [53]:
np_array = np.array([[1,2,3],[4,5,6]])
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()
np_array, tensor, np_array_back

(array([[1, 2, 3],
        [4, 5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]], dtype=torch.int32),
 array([[1, 2, 3],
        [4, 5, 6]]))

## Tensor operations

In [83]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

#### add

In [56]:
add1 = torch.add(x,y)
add2 = x + y
add1, add2

(tensor([5, 7, 9]), tensor([5, 7, 9]))

#### Subtract

In [57]:
sub1 = torch.subtract(x,y)
sub2 = x - y
sub1, sub2

(tensor([-3, -3, -3]), tensor([-3, -3, -3]))

#### divide

In [60]:
div1 = torch.true_divide(x,y)
div2 = x /y
div1, div2

(tensor([0.2500, 0.4000, 0.5000]), tensor([0.2500, 0.4000, 0.5000]))

In [61]:
t1 = torch.zeros(3)
t1.add_(x)
t2 = torch.zeros(3)
t2 += x
t1, t2

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

#### Exponentiation 

In [67]:
po1 = x.pow(2)
po2 = x**2
po1, po2

(tensor([1, 4, 9]), tensor([1, 4, 9]))

#### Comparision

In [69]:
comp1 = x > 0
comp2 = y < 0
comp1, comp2

(tensor([True, True, True]), tensor([False, False, False]))

#### Matrix multiplication

In [87]:
x1 = torch.tensor([[1,2,3],[4,5,6]])
y1 = torch.tensor([[4,5,6],[7,8,9]])
mm1 = x1.mm(y1.T)
mm2 = x1 @ y1.T
mm1, mm2

(tensor([[ 32,  50],
         [ 77, 122]]),
 tensor([[ 32,  50],
         [ 77, 122]]))

#### element wise mult

In [81]:
x1 * y1

tensor([[ 4, 10, 18],
        [28, 40, 54]])

#### dot product

In [84]:
torch.dot(x, y)

tensor(32)

In [95]:
# dim=0 : row, dim=1 column if no `dim` is passed it is applied on whole matrix
sum_x = torch.sum(x1, dim=1)
min_x = torch.min(x1, dim=0)
max_x = torch.max(x1)

print("sum_x: ", sum_x)
print("min_x: ", min_x)
print("max_x: ", max_x)

sum_x:  tensor([ 6, 15])
min_x:  torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))
max_x:  tensor(6)


In [97]:
abs_x = torch.abs(x) # elementwise abolute value
idx_max = torch.argmax(x1, dim=0) # index of max element
idx_min = torch.argmin(x1, dim=0) # index of min element

mean_x = torch.mean(x1.float(), dim=1) # mean of all values in dim=1
eq_xy = torch.eq(x1,y1)

eq_xy

tensor([[False, False, False],
        [False, False, False]])

In [101]:
sorted_value, indices = torch.sort(x1, dim=1, descending=True) # sort values in given dimention
sorted_value, indices

(tensor([[3, 2, 1],
         [6, 5, 4]]),
 tensor([[2, 1, 0],
         [2, 1, 0]]))

In [103]:
# clamp values between min and max. if lower than min then min, if upper than max then max
clamped_val = torch.clamp(x1, min=2, max=5) 
clamped_val

tensor([[2, 2, 3],
        [4, 5, 5]])

In [104]:
torch.any(x1) # if any of values is True (not False or zero)

tensor(True)

In [105]:
torch.all(x1) # if all of values is True (not False or zero)

tensor(True)

## Indexing

In [112]:
mat1 = torch.arange(25).reshape(5,5)
mat1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [113]:
# only row index 0
mat1[0, :]

tensor([0, 1, 2, 3, 4])

In [114]:
# rows index 1 and 2 (we have to set 1:3 because it is like [1,3) )
mat1[1:3, :]

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [115]:
# rows index 1 and 2 and columns 1 to 3
mat1[1:3, 1:4]

tensor([[ 6,  7,  8],
        [11, 12, 13]])

In [116]:
# rows index 1 and 3
mat1[[1,3],:]

tensor([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])

#### Condition to select values

In [119]:
mat1[mat1 < 15]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
mat1[(mat1 < 10) | (mat1 > 20)]

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 21, 22, 23, 24])

In [123]:
mat1[mat1.remainder(2)==0]

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [125]:
rows, cols = torch.where(mat1 > 15) # index where the condition fulfills
rows, cols

(tensor([3, 3, 3, 3, 4, 4, 4, 4, 4]), tensor([1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [126]:
 # where mat1 is bigger than 15 return that value, else power of 2
torch.where(mat1 > 15, mat1, mat1**2)

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]])

## Reshape tensor

In [133]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
# does not create anothe memory with 3x3 size but shows 1x9 as 3x3 (no performance loss)
x_3_3 = x.view(3,3) 
x_3_3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [135]:
# Copy values to 3x3 memory (performance loss)
x_3_3 = x.reshape(3,3) 
x_3_3

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [136]:
x_3_3.T # Transpose

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [142]:
x1 = torch.arange(0,5)
x2 = torch.arange(5,10)
x1, x2, x1.shape, x2.shape

(tensor([0, 1, 2, 3, 4]),
 tensor([5, 6, 7, 8, 9]),
 torch.Size([5]),
 torch.Size([5]))

In [138]:
# concatenate 2 tensors
torch.cat((x1, x2), dim=0)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
torch.cat((x1, x2), dim=1) # not gonna work since we don't have row in our shape

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [144]:
x1 = x1.reshape(1,5)
x2 = x2.reshape(1,5)
torch.cat((x1, x2), dim=0)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])